### ISSUE TITLE
[TODO] User Profile page updates 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#152]
We recently added the User Profile feature to this project.

It's not complete. It is accessible from click on the (R) in the top bar navigation and click on Profile.

Use @mui/material and @mui/icons material packages to:

- [ ] Display users profile pic/avatar 
  - [ ] See #101 
- [ ] Location (will need some internationalization)
- [ ] Occupation / Career / Work/ Employment 
- [ ] Education / School(s)
- [ ] Age (including a feature to hide the age, etc if the user doesn't want displayed)
- [ ] Development Skills (Frameworks, Languages, Frontend, Backend, DevOps, Game Developer, etc)
- [ ] Favorite editor/IDE
- [ ] Operating System / OS (Windowe, Mac, Linux Unix)
- [ ] Add a Edit Profile select so the user can update their profile.
- [ ] Number of likes, follows, etc. 
- [ ] Website or CV or Portfolio link
- [ ] GitHub, GitLab, etc link
- [ ] Stream link (If streamer)

There might be some backend tasks for this.  We can create a backend issue or task for this. 

@LOGESH-B

**Comment by gbowne1** [comment]
The current /profile screen:

![Screenshot 2023-08-29 at 14-52-35 React App](https://github.com/gbowne1/codebooker/assets/47549872/d33922d2-b662-4abd-803e-8bbe493b2995)

**Comment by BlackBond06** [comment]
@gbowne1, I have assigned this issue to myself, and I'll will start working on it immediately.

**Comment by gbowne1** [comment]
Ok great thank you @BlackBond06

**Comment by BlackBond06** [comment]
I just realised that ideally, this feature should build upon the create user profile, issue #127. Now since this issue hasnt been completed, I am at a loss on how to go about it. I would like to work on that issue also if its ok with the assignee. This will help me build upon the create user profile so I can implement the update profile feature I have been assigned to.

**Comment by BlackBond06** [comment]
@gbowne1, @LOGESH-B 

I want to share my thought process on this feature, to get your feedback before I begin working on it.

So  ideally, the following is the flow of events a user passes through before reaching this feature:
User signup/login ---- User creates profile ---- User access profile (from R icon menu) ---- User updates profile (this page should ideally show the details of the user obtained during profile creation).

Now, this is how I intend to approach this feature:
1. User logs in.
2. If the user hasn't created a profile yet (which is the case for all users currently), they will receive a prompt, possibly a modal, asking them to create a profile. They can choose to accept or cancel.
3. If accepted, the user will be presented with a profile creation form to complete and create a profile.
4. If denied, the prompt disappears, but it will reappear every time the user logs in until they create a profile.

Additionally, if a user hasn't created a profile, access to the profile component (accessible via the profile icon in the R menu) remains hidden because logically, a user can't access and update a profile that hasn't been created.

Because we haven't added the 'create profile' feature yet, I'll work on it at the same time as the 'update profile' feature. Since the 'update profile' feature will likely depend on the same schema model properties used in the 'create profile' feature."

**Comment by gbowne1** [comment]
@BlackBond06 

There originally was two separate issues:

One for creating the actual profile page (the static page where profile details are displayed)


One for creating a page to create the profile (a form to enter profile details that would get saved to the database)

I realize  I did not word the title and first post in this particular issue thread/post so it may have not been clear that this particular issue covers enhancement of the already existing profile page.

This particular issue covers the first of those two, creating a profile 

The screenshot I posted in the thread here is the profile page accessible from the user menu by clicking Profile.

First of all the edit button does nothing.  The edit profile button would be there only for the logged in user to edit details about them.  

Your second post earlier is definitely the approach I would take.  Either way contributors and collaborators are welcome to create TODO and other types of issues.

**Comment by BlackBond06** [comment]
So do I need to also assign myself issue #127 ?

**Comment by gbowne1** [comment]
If you want to work on both of those things, yes, you can assign yourself #127 as well.  They are related issue.

**Comment by gbowne1** [comment]
and probably also #101, so that we get some test user images, test profile data, etc.
